name: Deploy Cloud Functions
on:
  # 手動or特定ブランチにPush時に実行
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  deploy-job:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'decode'
      name: 'Decode credential'
      env:
        ENCODED_GCP_CREDENTIAL: ${{ secrets.ENCODED_GCP_CREDENTIAL }}
      run: |
        echo '${{ secrets.GCP_CREDENTIAL }}' | base64 --decode > credential.json

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.ENCODED_GCP_CREDENTIAL }}'

    - id: 'deploy'
      name: 'Deploy Cloud Functions'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'test-githubactions-deploy-develop'
        runtime: 'python38'
        region: asia-northeast1
        entry_point: hello_world
        service_account_email: gha-cloudfunctions-deploy@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
        source_dir: ./test-githubactions-deploy

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'