name: Deploy Cloud Functions
on:
  # 手動orプルリククローズ時にに実行
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy-job:
    # マージが確認できたら以下ジョブを実行
    if: github.event.pull_request.merged == true
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIAL }}'

    - id: 'deploy'
      name: 'Deploy Cloud Functions'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'test-githubactions-deploy'
        runtime: 'python38'
        region: asia-northeast1
        entry_point: hello_world
        service_account_email: gha-cloudfunctions-deploy@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
        source_dir: ./test-githubactions-deploy

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'